### ISSUE TITLE
Общий класс Timer

### ISSUE THREAD

**Issue by fedosgad** [GyverLibs/GyverTimers#2]
Есть ли конкретные причины, почему у всех таймеров нет общего чисто виртуального класса-предка `Timer` (производительность, занимаемая память, что-то еще)?
Такой класс сильно упростил бы подключение таймеров (не обязательно жестко привязывать периферию к конкретному таймеру в библиотеке, достаточно принять `Timer*` как параметр конструктора).
Если явных причин нет, готов оформить Pull Request с таким функционалом.

**Comment by GyverLibs** [comment]
Конкретная причина - изначальный автор библиотеки не умеет в наследование

**Comment by fedosgad** [comment]
Исследовал вопрос - наследовать классы на AVR (а эта библиотека только под них и заточена) не очень хорошая идея.
Толковое описание: https://habr.com/ru/companies/amperka/articles/264041/ .
Поэтому Issue закрываю.

**Comment by GyverLibs** [comment]
Да, видел кстати эту статью. Тогда нет смысла, столько рамы в трубу улетит.. мно можно на шаблонах сделать при большом желании, они compile time
