### ISSUE TITLE
outputState doesn't work for LOW state

### ISSUE THREAD

**Issue by melehin** [GyverLibs/GyverTimers#4]
Hi!

Thank you for great work under all libraries!
Just i found this issue by my oscilloscope.

I've used this snippet to change output pin value to LOW.
```cpp
void stop_timer(){
  Timer1.stop();
  Timer1.outputState(CHANNEL_B, LOW);
}
```

Change to LOW state doesn't work because bit OR on zero. 
```cpp
 | (state << FOC1A)
```
when state = LOW = 0
then 0 << FOC1A = 0 and so on

https://github.com/GyverLibs/GyverTimers/blob/418c580b68ba64fe6fef5fee100b219103d48b5b/src/GyverTimers.cpp#L76

**Comment by Nich1con** [comment]
> Hi!
> 
> Thank you for great work under all libraries! Just i found this issue by my oscilloscope.
> 
> I've used this snippet to change output pin value to LOW.
> 
> ```c++
> void stop_timer(){
>   Timer1.stop();
>   Timer1.outputState(CHANNEL_B, LOW);
> }
> ```
> 
> Change to LOW state doesn't work because bit OR on zero.
> 
> ```c++
>  | (state << FOC1A)
> ```
> 
> when state = LOW = 0 then 0 << FOC1A = 0 and so on
> 
> https://github.com/GyverLibs/GyverTimers/blob/418c580b68ba64fe6fef5fee100b219103d48b5b/src/GyverTimers.cpp#L76

(TCCR1C & 0x7F) will clear only FOC1A bit, and if state = 0, this bit stay in LOW state. If state = 1, FOC1A bit will write as HIGH

**Comment by melehin** [comment]
I got it. Thx.

**Comment by GyverLibs** [comment]
!(en)[https://kartinkof.club/uploads/posts/2022-03/1648235643_1-kartinkof-club-p-o-vi-iz-anglii-mem-kot-1.jpg]
