### ISSUE TITLE
сколько осталось до конца таймера

### ISSUE THREAD

**Issue by slidekor** [GyverLibs/GyverTimers#7]
я использую м5 коре2 как мне вывести время которое осталось до конца таймера, хотя бы в ком порт,а там разберусь. буду благодарен за помощь

**Comment by GyverLibs** [comment]
![image](https://github.com/user-attachments/assets/cbbe4398-f053-4026-b843-6cba7ad51019)

**Comment by slidekor** [comment]
как я понимаю если онa совместим только с этими мк, она не должна работать на м5?

**Comment by GyverLibs** [comment]
Естественно

**Comment by slidekor** [comment]
если естественно тогда почему у меня она работает?

**Comment by GyverLibs** [comment]
Этого просто не может быть :)

**Comment by slidekor** [comment]
я могу завтра прикрепить видео и код что у меня все работает

**Comment by GyverLibs** [comment]
Ну, я быстрее в деда мороза поверю :D библиотека не будет даже компилироваться на этой архитектуре, не то что работать
